import chess
import numpy as np
import tensorflow as tf
from board_utils import board_to_tensor

def test_inference():
    print("Loading optimized AI Model...")
    # Load the model generated by train.py
    model = tf.keras.models.load_model("best_chess_model.keras")
    
    board = chess.Board()
    print("\nEvaluating Starting Position:")
    print(board)
    
    # Convert and reshape for the neural network
    tensor = board_to_tensor(board)
    tensor_batch = np.expand_dims(tensor, axis=0)
    
    # Get the prediction
    evaluation = model.predict(tensor_batch, verbose=0)
    print(f"\nAI Evaluation Score: {evaluation[0][0]:.3f}")

if __name__ == "__main__":
    test_inference()